### ISSUE TITLE
ReferenceError: PIXI is not defined

### ISSUE THREAD

**Issue by nazywamsiepawel** [bma73/revolt-fx#4]
Hi,

Simply importing the library seems to be causing the issue below. Any idea on what I might be doing wrong? I'm using Next.js + Typescript and loading the component dynamically. 

```
ReferenceError: PIXI is not defined
    at Object../node_modules/revolt-fx/lib/Sprite.js (Sprite.js:41)
    at __webpack_require__ (bootstrap:791)
    at fn (bootstrap:150)
    at Object../node_modules/revolt-fx/lib/FX.js (FX.js:46)
    at __webpack_require__ (bootstrap:791)
    at fn (bootstrap:150)
    at Object../node_modules/revolt-fx/lib/index.js (index.js:3)
    at __webpack_require__ (bootstrap:791)
    at fn (bootstrap:150)
    at Module../components/game.tsx (1.5dd028ef129e64d7c82a.hot-update.js:24)
    at __webpack_require__ (bootstrap:791)
    at fn (bootstrap:150)
```

My imports:

```
import * as PIXI from "pixi.js";
import {FX} from 'revolt-fx'
let fx = new FX()
```

**Comment by bma73** [comment]
Should be fixed with the latest upate

**Comment by yuensunn** [comment]
Hi @bma73 ,

Tested on the new version. The problem still persist. 
My currently work around is declaring `window.PIXI = PIXI` in `index.js`

**Comment by Shmo** [comment]
I also get this with latest npm version "revolt-fx": "^1.1.1".
